import { EDGPRESS_GITHUB } from "./constants";
import { deriveWorkerName } from "../wizard/site-slug";
import type { WizardSetupConfig } from "../wizard/session";

export type WranglerBindingConfig = {
	workerName: string;
	d1: { name: string; id: string };
	kv: { name: string; id: string };
	r2: { name: string };
};

export type BetterAuthVars = {
	betterAuthUrl: string;
	trustedOrigins: string;
	workersDevUrl: string;
	customDomainUrl?: string;
};

const DEFAULT_RATE_LIMIT_VARS = {
	RATE_LIMIT_LOGIN_MAX: "10",
	RATE_LIMIT_LOGIN_WINDOW_MIN: "5",
	RATE_LIMIT_REGISTER_MAX: "10",
	RATE_LIMIT_REGISTER_WINDOW_MIN: "10",
	RATE_LIMIT_UPLOAD_MAX: "100",
	RATE_LIMIT_UPLOAD_WINDOW_MIN: "10",
	RESEND_FROM: "contato@amb1.io",
} as const;

export function resolveBetterAuthVars(input: {
	config: WizardSetupConfig;
	workerName: string;
	workersSubdomain: string;
}): BetterAuthVars {
	const workersDevUrl = `https://${input.workerName}.${input.workersSubdomain}.workers.dev`;

	if (input.config.associateDomain && input.config.zoneName) {
		const customDomainUrl = `https://${input.config.zoneName}`;
		return {
			betterAuthUrl: customDomainUrl,
			trustedOrigins: `${workersDevUrl},${customDomainUrl}`,
			workersDevUrl,
			customDomainUrl,
		};
	}

	return {
		betterAuthUrl: workersDevUrl,
		trustedOrigins: workersDevUrl,
		workersDevUrl,
	};
}

function tomlString(value: string): string {
	return JSON.stringify(value);
}

export function buildWranglerToml(input: {
	bindings: WranglerBindingConfig;
	auth: BetterAuthVars;
}): string {
	const { bindings, auth } = input;

	return `# Generated by EdgePress Wizard — do not commit
name = ${tomlString(bindings.workerName)}
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"
binding = "ASSETS"

[vars]
BETTER_AUTH_URL = ${tomlString(auth.betterAuthUrl)}
BETTER_AUTH_TRUSTED_ORIGINS = ${tomlString(auth.trustedOrigins)}
RATE_LIMIT_LOGIN_MAX = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_LOGIN_MAX)}
RATE_LIMIT_LOGIN_WINDOW_MIN = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_LOGIN_WINDOW_MIN)}
RATE_LIMIT_REGISTER_MAX = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_REGISTER_MAX)}
RATE_LIMIT_REGISTER_WINDOW_MIN = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_REGISTER_WINDOW_MIN)}
RATE_LIMIT_UPLOAD_MAX = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_UPLOAD_MAX)}
RATE_LIMIT_UPLOAD_WINDOW_MIN = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_UPLOAD_WINDOW_MIN)}
RESEND_FROM = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RESEND_FROM)}

[[d1_databases]]
binding = "DB"
database_name = ${tomlString(bindings.d1.name)}
database_id = ${tomlString(bindings.d1.id)}
migrations_dir = "./drizzle"

[[kv_namespaces]]
binding = "CACHE"
id = ${tomlString(bindings.kv.id)}

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = ${tomlString(bindings.r2.name)}

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
`;
}

/** Env var written on the build trigger; holds base64-encoded wrangler.toml. */
export const WRANGLER_TOML_ENV_KEY = "WIZARD_WRANGLER_TOML_B64";

/** Wrangler reads this during GitHub Builds (migrate + seed on remote D1). */
export const CLOUDFLARE_API_TOKEN_ENV_KEY = "CLOUDFLARE_API_TOKEN";

/**
 * Same remote DB flow as EdgePress `db:migrate:remote` + `db:seed:remote`:
 * wrangler migrations apply, then execute committed drizzle/seed/seed-remote.sql.
 * Wizard-specific data (admin user, site name) is applied after deploy via POST /api/setup.
 */
export function buildWranglerBuildCommand(d1DatabaseName: string): string {
	const writeToml = `node -e "require('fs').writeFileSync('wrangler.toml',Buffer.from(process.env.${WRANGLER_TOML_ENV_KEY},'base64'))"`;
	const db = JSON.stringify(d1DatabaseName);
	return [
		writeToml,
		`npx wrangler d1 migrations apply ${db} --remote -c wrangler.toml`,
		`npx wrangler d1 execute ${db} --remote --file=./drizzle/seed/seed-remote.sql -c wrangler.toml`,
		"npm run build",
	].join(" && ");
}

export function buildWranglerBuildEnvironment(input: {
	wranglerToml: string;
	apiToken: string;
}): Record<string, { value: string; is_secret: boolean }> {
	return {
		[WRANGLER_TOML_ENV_KEY]: {
			value: Buffer.from(input.wranglerToml, "utf8").toString("base64"),
			is_secret: false,
		},
		[CLOUDFLARE_API_TOKEN_ENV_KEY]: {
			value: input.apiToken,
			is_secret: true,
		},
	};
}

export function buildWranglerDeployCommand(): string {
	return EDGPRESS_GITHUB.deployCommand;
}

export function buildWranglerConfigForSite(input: {
	config: WizardSetupConfig;
	apiToken: string;
	bindings: Omit<WranglerBindingConfig, "workerName"> & {
		d1: { name: string; id: string };
		kv: { name: string; id: string };
		r2: { name: string };
	};
	workersSubdomain: string;
}) {
	const workerName = deriveWorkerName(input.config.siteName);
	const auth = resolveBetterAuthVars({
		config: input.config,
		workerName,
		workersSubdomain: input.workersSubdomain,
	});
	const wranglerToml = buildWranglerToml({
		bindings: { ...input.bindings, workerName },
		auth,
	});

	return {
		workerName,
		auth,
		wranglerToml,
		buildCommand: buildWranglerBuildCommand(input.bindings.d1.name),
		buildEnvironment: buildWranglerBuildEnvironment({
			wranglerToml,
			apiToken: input.apiToken,
		}),
		deployCommand: buildWranglerDeployCommand(),
	};
}
