import { EDGPRESS_GITHUB } from "./constants";
import { deriveWorkerName } from "../wizard/site-slug";
import type { WizardSetupConfig } from "../wizard/session";

export type WranglerBindingConfig = {
	workerName: string;
	d1: { name: string; id: string };
	kv: { name: string; id: string };
	r2: { name: string };
};

export type BetterAuthVars = {
	betterAuthUrl: string;
	trustedOrigins: string;
	workersDevUrl: string;
	customDomainUrl?: string;
};

const DEFAULT_RATE_LIMIT_VARS = {
	RATE_LIMIT_LOGIN_MAX: "10",
	RATE_LIMIT_LOGIN_WINDOW_MIN: "5",
	RATE_LIMIT_REGISTER_MAX: "10",
	RATE_LIMIT_REGISTER_WINDOW_MIN: "10",
	RATE_LIMIT_UPLOAD_MAX: "100",
	RATE_LIMIT_UPLOAD_WINDOW_MIN: "10",
	RESEND_FROM: "contato@amb1.io",
} as const;

export function resolveBetterAuthVars(input: {
	config: WizardSetupConfig;
	workerName: string;
	workersSubdomain: string;
}): BetterAuthVars {
	const workersDevUrl = `https://${input.workerName}.${input.workersSubdomain}.workers.dev`;

	if (input.config.associateDomain && input.config.zoneName) {
		const customDomainUrl = `https://${input.config.zoneName}`;
		return {
			betterAuthUrl: customDomainUrl,
			trustedOrigins: `${workersDevUrl},${customDomainUrl}`,
			workersDevUrl,
			customDomainUrl,
		};
	}

	return {
		betterAuthUrl: workersDevUrl,
		trustedOrigins: workersDevUrl,
		workersDevUrl,
	};
}

function tomlString(value: string): string {
	return JSON.stringify(value);
}

export function buildWranglerToml(input: {
	bindings: WranglerBindingConfig;
	auth: BetterAuthVars;
}): string {
	const { bindings, auth } = input;

	return `# Generated by EdgePress Wizard — do not commit
name = ${tomlString(bindings.workerName)}
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"
binding = "ASSETS"

[vars]
BETTER_AUTH_URL = ${tomlString(auth.betterAuthUrl)}
BETTER_AUTH_TRUSTED_ORIGINS = ${tomlString(auth.trustedOrigins)}
RATE_LIMIT_LOGIN_MAX = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_LOGIN_MAX)}
RATE_LIMIT_LOGIN_WINDOW_MIN = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_LOGIN_WINDOW_MIN)}
RATE_LIMIT_REGISTER_MAX = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_REGISTER_MAX)}
RATE_LIMIT_REGISTER_WINDOW_MIN = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_REGISTER_WINDOW_MIN)}
RATE_LIMIT_UPLOAD_MAX = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_UPLOAD_MAX)}
RATE_LIMIT_UPLOAD_WINDOW_MIN = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RATE_LIMIT_UPLOAD_WINDOW_MIN)}
RESEND_FROM = ${tomlString(DEFAULT_RATE_LIMIT_VARS.RESEND_FROM)}

[[d1_databases]]
binding = "DB"
database_name = ${tomlString(bindings.d1.name)}
database_id = ${tomlString(bindings.d1.id)}
migrations_dir = "./drizzle"

[[kv_namespaces]]
binding = "CACHE"
id = ${tomlString(bindings.kv.id)}

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = ${tomlString(bindings.r2.name)}

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
`;
}

/** Shell command run by Workers Builds: writes wrangler.toml then runs the EdgePress build. */
export function buildWranglerBuildCommand(wranglerToml: string): string {
	const encoded = Buffer.from(wranglerToml, "utf8").toString("base64");
	return `node -e "require('fs').writeFileSync('wrangler.toml', Buffer.from('${encoded}', 'base64'))" && npm run build`;
}

export function buildWranglerDeployCommand(): string {
	return EDGPRESS_GITHUB.deployCommand;
}

export function buildWranglerConfigForSite(input: {
	config: WizardSetupConfig;
	bindings: Omit<WranglerBindingConfig, "workerName"> & {
		d1: { name: string; id: string };
		kv: { name: string; id: string };
		r2: { name: string };
	};
	workersSubdomain: string;
}) {
	const workerName = deriveWorkerName(input.config.siteName);
	const auth = resolveBetterAuthVars({
		config: input.config,
		workerName,
		workersSubdomain: input.workersSubdomain,
	});
	const wranglerToml = buildWranglerToml({
		bindings: { ...input.bindings, workerName },
		auth,
	});

	return {
		workerName,
		auth,
		wranglerToml,
		buildCommand: buildWranglerBuildCommand(wranglerToml),
		deployCommand: buildWranglerDeployCommand(),
	};
}
